
# Use python as its the simplest language which can run a test script
language: python

before_install:
    # Print out the bash version
    - sudo /bin/bash --version
    # Install dependencies
    - sudo apt-get install shunit2
    # Debug output the contents of this script which is causing errors
    - echo -e "\n\n\n"
    - sudo ls -lah /etc/profile.d
    - sudo cat /etc/profile.d/phpenv.sh
    - echo -e "\n\n\n"

# Create a minecraft user for testing
install:
    - sudo adduser --system minecraft
    
# Run the test script
script: sudo /bin/bash ./test.sh